### ISSUE TITLE
Infografia 

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Nayee123#2]
[Gestión de proyectos de software Nayeli Anai González López .pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-gestion-de-proyectos-de-software-Nayee123/files/9419039/Gestion.de.proyectos.de.software.Nayeli.Anai.Gonzalez.Lopez.pdf)

**Comment by bg55-a** [comment]
Calificación: 20%

**Comment by JazminloRI** [comment]
Calificación Final: 20%

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
